spring.application.name=TPI-PIV

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.wmyteteupbxwbgtfylcj
spring.datasource.password=programacionCUATRO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=SECRET_PROG4_26_BANCO_PAISAJE_123456
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000